const images = [
  {
    id: 1,
    vibe: "Calm",
    color: "Blue",
    title: "Metallic Chic",
    owner: "Shopify",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/2.jpg",
    colorA: "#EDE8F5",
    colorB: "#7091E6",
    industry: "Corporate",
    description:
      "This website features a sophisticated color palette infused with metallic accents, layered over a blue-toned gradient that creates a stylish 3D effect. This design choice enhances Shopify's product updates, fostering a serene atmosphere that sparks curiosity in viewers.",
  },
  {
    id: 2,
    vibe: "Vintage",
    color: ["Black", "Blue"],
    owner: "Prometheus",
    title: "Deep Vintage Mood",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/3.jpg",
    colorA: "#244855",
    colorB: "#FBE9D0",
    industry: "Sports",
    description:
      "The Prometheus website's vintage color scheme intertwines rustic terracotta, a gradient of profound midnight blue, and the striking obsidian black of the car, heightened by metallic accents that infuse a touch of futuristic allure into the composition.",
  },
  {
    id: 3,
    vibe: "Calm",
    color: "Dark",
    owner: "Refire",
    title: "Cool and Collected",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/4.jpg",
    colorA: "#AFDDE5",
    colorB: "#003135",
    industry: "Creative",
    description:
      "Rich deep teals mingle with vibrant metallics, crafting an avant-garde color spectrum that dynamically shifts from shadowy depths to luminous highlights within an animated video. This screenshot beautifully encapsulates the website's vivid palette. Explore the site to fully immerse yourself in its visual splendor.",
  },
  {
    id: 4,
    vibe: "Earthy",
    color: "Slate Gray",
    owner: "Kozowood",
    title: "Earthy and Serene",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/5.jpg",
    colorA: "#AC8968",
    colorB: "#A69080",
    industry: "E-commerce",
    description:
      "The site's color scheme is anchored by grounding sandy tones, imparting a reassuring warmth and stability. Slate gray text contrasts boldly against the clay backdrop, while accents of sky blue and fern green inject vibrant bursts of color, creating a harmonious visual experience.",
  },
  {
    id: 5,
    vibe: "Modern",
    color: ["Green", "Pink", "Red/Raspberry"],
    owner: "Brewdistrict 24",
    title: "Texture and Contrast",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/6.gif",
    colorA: "#63776c",
    colorB: "#7a97a2",
    industry: "E-commerce",
    description:
      "This website boasts not one, but four distinct color schemes, each representing a different type of beer and accessible via a user-friendly button. Each scheme features a textured, subdued background paired with a vivid accent color: raspberry and green, teal and pink, blue-gray and orange, and olive green and light orange, offering visitors a spectrum of visual experiences to choose from.",
  },
  {
    id: 6,
    vibe: "Modern",
    industry: "Corporate",
    color: ["Black", "Blue"],
    owner: "Lusion",
    title: "Mechanical and Floaty",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/7.jpg",
    colorA: "#141619",
    colorB: "#0121C0",
    description:
      "The site's subdued mellow tone is achieved through nearly black text set against a light gray background, providing a serene backdrop that contrasts with vibrant blue accents in the introductory video and scrolling squiggles. Visual harmony is maintained by shapes in the header matching the text and background colors, ensuring a balanced and cohesive aesthetic throughout.",
  },
  {
    id: 7,
    vibe: "Modern",
    color: ["Black", "Blue"],
    owner: "Locomotive",
    title: "Pixel Intensity",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/8.gif",
    colorA: "#2c57cb",
    colorB: "#1b0b10",
    industry: "Creative",
    description:
      "In the opening scene of the website's video-based hero section, a striking red and black figure dominates against a vibrant red backdrop. Her eyes are adorned with pixels ranging from black to red, punctuated by contrasting blue lights. The text adopts a matching blue hue that mirrors the flickering lights above. Click the link to experience the full video and immerse yourself in its dynamic effects.",
  },
  {
    id: 8,
    vibe: "Modern",
    color: ["Black", "Blue", "Red/Raspberry"],
    owner: "C2 Montreal",
    title: "Gradient Pop",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/9.jpg",
    colorA: "#C50990",
    colorB: "#F95CA4",
    industry: "Technology",
    description:
      "The color scheme of this website revolves around a series of interlaced gradient circles, creating a vibrant palette. Dominated by sky blue, salmon-pink, and bright orange as primary hues, it also features accent colors in black and neon green strategically used to highlight crucial information such as dates and calls to action. This blend of colors not only enhances visual appeal but also ensures key elements stand out effectively.",
  },
  {
    id: 9,
    vibe: "Vintage",
    industry: "Corporate",
    color: "Slate Gray",
    owner: "Jeff Koons Moon Phases",
    title: "Cosmic Artistry",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/10.jpg",
    colorA: "#212A31",
    colorB: "#748D92",
    description:
      "The selected color scheme is perfectly suited for a website dedicated to moon phase sculptures. Featuring a blend of gray-washed white, space blue, slate gray, and subtle gradient effects in the text, it evokes an authentic cosmic atmosphere, aligning seamlessly with the theme of lunar phases.",
  },
  {
    id: 10,
    vibe: "Calm",
    color: "Pink",
    owner: "Loket Design",
    title: "Vibrant but Calm",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/11.jpg",
    colorA: "#EBE9E1",
    colorB: "#E43D12",
    industry: "E-commerce",
    description:
      "This website boldly opts for muted red text, a color not typically associated with readability, yet it achieves harmony with a creamy-gray background. Adding another dimension to the palette, a central pink object enhances the overall depth and visual interest of the design.",
  },
  {
    id: 11,
    vibe: "Lively",
    industry: "Corporate",
    color: ["Pink", "White/Creamy"],
    title: "Lively and Inviting",
    owner: "Anton & Irene",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website11.jpg",
    colorA: "#E7717D",
    colorB: "#AFD275",
    description:
      "The delightful blend of candy pink, green-yellow, lavender gray, and pastel brown creates an inviting and vibrant image, perfect for designs aiming to captivate and charm their audience.",
  },
  {
    id: 12,
    vibe: "Modern",
    color: ["Black", "Dark"],
    owner: "Bert",
    title: "Striking and Simple",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website12.jpg",
    colorA: "#0B0C10",
    colorB: "#66FCF1",
    industry: "Technology",
    description:
      "This minimalist yet captivating design is hard to ignore. The dark, smoky black background paired with an electric blue hue creates a striking and effective color scheme that is versatile and suitable for a wide range of projects.",
  },
  {
    id: 13,
    vibe: "Lively",
    color: ["White/Creamy", "Red/Raspberry"],
    owner: "BrightMedia",
    title: "Red and Lively",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website13.jpg",
    colorA: "#E3E2DF",
    colorB: "#911750",
    industry: "Creative",
    description:
      "Inspired by the red Polish flag, this attractive website blends dark scarlet red with deep pink accents against a backdrop of light gray. The result is a lively and creative design that maintains a refined aesthetic, utilizing a minimalist approach with varying shades of the same hue.",
  },
  {
    id: 14,
    vibe: "Artistic",
    color: "White/Creamy",
    owner: "Julie Flogeac",
    title: "Artsy and Creative",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website14.jpg",
    colorA: "#EFE2BA",
    colorB: "#4056A1",
    industry: "Creative",
    description:
      "This vibrant combination of goldenrod, vermillion, dark blue, and Dutch white breathes life into the artsy and creative design of an online archive for musical works.",
  },
  {
    id: 15,
    vibe: "Calm",
    color: "White/Creamy",
    owner: "Epic",
    title: "Elegant Yet Approachable",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website15.jpg",
    colorA: "#EE2DC",
    colorB: "#123C69",
    industry: "Creative",
    description:
      "This distinctive mix of skin tones alongside sophisticated colors like dark imperial blue and ruby creates an ideal color scheme for designs conveying nuanced messages. It strikes a balance between being reserved yet approachable, and sophisticated yet fun, effectively communicating subtle and complex ideas with its pleasing visual appeal.",
  },
  {
    id: 16,
    vibe: "Modern",
    color: ["Drak", "Green"],
    owner: "MediaMonks",
    title: " Sleek and Futuristic",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website16.jpg",
    colorA: "#116466",
    colorB: "#2C3531",
    industry: "Technology",
    description:
      "The site's subdued mellow tone is achieved through nearly black text set against a light gray background, providing a serene backdrop that contrasts with vibrant blue accents in the introductory video and scrolling squiggles. Visual harmony is maintained by shapes in the header matching the text and background colors, ensuring a balanced and cohesive aesthetic throughout.",
  },
  {
    id: 17,
    vibe: "Artistic",
    color: "Dark",
    owner: "eDesign Interactive",
    title: " Innovative and Audacious",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website17.jpg",
    colorA: "#272727",
    colorB: "#FFE400",
    industry: "Creative",
    description:
      "This bold combination of Portland Orange, vivid yellow, and jade set against a dark gray, almost black background demands attention. With its daring and energetic vibe, this color palette is ideal for achieving a contemporary and audacious aesthetic.",
  },
  {
    id: 18,
    vibe: "Modern",
    color: ["Slate Gray", "Red/Raspberry", "Green"],
    owner: "HAUS",
    title: "Texturized and Dynamic",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website18.jpg",
    colorA: "#2E151B",
    colorB: "#376E6F",
    industry: "Technology",
    description:
      "Dark sienna, charcoal, and a burst of pale red violet converge in this sophisticated color scheme, offering an elegant, futuristic, and dynamic look and feel. Versatile enough to enhance modern corporate reports as well as magazines and editorial content, this palette exudes a sense of timeless style with a contemporary edge.",
  },
  {
    id: 19,
    vibe: "Lively",
    color: "White/Creamy",
    owner: "Gusto Ids",
    title: "Minimal Yet Warm",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website19.jpg",
    colorA: "#EAE7DC",
    colorB: "#EA584F",
    industry: "E-commerce",
    description:
      "Eggshell white, dark vanilla, and taupe gray form the minimalist base of this warm and inviting website, accented by pops of jelly bean red. The strategic use of energetic color highlights throughout the design enhances its elegance while maintaining an inviting atmosphere.",
  },
  {
    id: 20,
    vibe: "Vintage",
    industry: "Corporate",
    color: ["Black", "Blue", "Dark"],
    owner: "FCINQ",
    title: "Vivid and Sharp",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website20.jpg",
    colorA: "#44318D",
    colorB: "#ffffff",
    description:
      "Dark cerise, royal purple, and dark slate blue intertwine to create a stunning and captivating website. The deep cerise serves as a striking accent color against a backdrop of dark purple, guiding the viewer's gaze directly to the navigation menu upon arrival.",
  },
  {
    id: 21,
    vibe: "Modern",
    color: "Blue",
    title: "Clean and Energetic",
    owner: "Change Digital",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website21.jpg",
    colorA: "#84CEEB",
    colorB: "#8860D0",
    industry: "Technology",
    description:
      "The blend of blueberry, sky blue, and amethyst on this site creates a visually appealing palette that simultaneously energizes and calms the viewer. This refreshing combination evokes both peace and vitality, making it ideal for designs aimed at eliciting positive emotions and leaving a lasting impression.",
  },
  {
    id: 22,
    vibe: "Vintage",
    industry: "Corporate",
    color: "Green",
    owner: "Watson/DG",
    title: "Corporate and Traditional",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website22.jpg",
    colorA: "#88BDBC",
    colorB: "#112D32",
    description:
      "For those seeking a muted and corporate aesthetic, this color scheme harmonizes shades of green, blue, and brown, embodying professionalism and reliability. Colors like Phthalo Green, dark slate gray, and pewter blue are strategically employed to achieve this sophisticated yet approachable look.",
  },
  {
    id: 23,
    vibe: "Vintage",
    color: ["Blue", "Green"],
    owner: "Supremo",
    title: "Blue and Refreshing",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website23.jpg",
    colorA: "#25274D",
    colorB: "#2E9CAA",
    industry: "Technology",
    description:
      "A palette ranging from bright lapis lazuli blue to serene aqua blue creates a reserved yet captivating color scheme. Suitable for a wide array of visuals, from muted corporate projects to design-oriented contexts, this combination exudes versatility and beauty.",
  },
  {
    id: 24,
    vibe: "Modern",
    industry: "Corporate",
    color: "Green",
    owner: "Umwelt A/S",
    title: "Clean and Modern",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website24.jpg",
    colorA: "#EAAFA9",
    colorB: "#FEFFFF",
    description:
      "A harmonious blend of myrtle green and keppel is complemented by accents of azureish white and plain white, creating a simple yet highly effective color combination.",
  },
  {
    id: 25,
    vibe: "Earthy",
    color: "Blue",
    owner: "Waaark",
    title: "Vibrant and Elegant",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website25.jpg",
    colorA: "#A8D0E6",
    colorB: "#F76C6C",
    industry: "Healthcare",
    description:
      "This bright and elegant color scheme combines a highly saturated light cold blue with complementary shades like dark slate blue and pale cornflower blue. This combination is elegantly complemented by a bright and vivid shade of pink.",
  },
  {
    id: 26,
    vibe: "Lively",
    color: "White/Creamy",
    owner: "Five Hundred",
    title: "Youthful and Fun",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website26.jpg",
    colorA: "#17E930",
    colorB: "#FFFFFF",
    industry: "Education",
    description:
      "This playful and colorful scheme blends several vibrant hues: bright turquoise, tangerine yellow, and dark orchid.",
  },
  {
    id: 27,
    color: ["Black", "Dark"],
    industry: "Corporate",
    vibe: "Artistic",
    owner: "Immersive Garden",
    title: "Gorgeous Contrast",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website27.jpg",
    colorA: "#222629",
    colorB: "#6B6E70",
    description:
      "This sleek and ultra-modern site features an elegant and eye-catching combination with effective contrast. The bright yellow-green complements the black and gray background beautifully.",
  },
  {
    id: 28,
    vibe: "Earthy",
    color: "Slate Gray",
    owner: "SMFB",
    title: "Effective Accent Colors",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website28.jpg",
    colorA: "#9D8D8F",
    colorB: "#4AED26",
    industry: "Education",
    description:
      "This site strategically employs a vibrant accent color to direct the viewers' gaze. The bright yellow captures attention initially at the title, guides it along the path up the mountain, and finally directs it towards the call-to-action buttons positioned at the bottom of the page.",
  },
  {
    id: 29,
    vibe: "Modern",
    color: "Green",
    owner: "Nurture Digital",
    title: "Modernity in Full Bloom",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website29.jpg",
    colorA: "#65CCB8",
    colorB: "#3B945E",
    industry: "E-commerce",
    description:
      "The blend of ocean green, aquamarine, and sea green effectively conveys a sense of modernity while embodying themes of life and fertility. This color scheme harmoniously aligns with the central message of the site, which emphasizes concepts such as digital innovation, nurturing growth, and blooming potential.",
  },
  {
    id: 30,
    vibe: "Earthy",
    color: ["Blue", "White/Creamy"],
    owner: "Born05",
    title: " Close to Nature",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website30.jpg",
    colorA: "#F7F9FB",
    colorB: "#31708E",
    industry: "Healthcare",

    description:
      "This earthy combination of greens alongside a range of blues, from pale cerulean to teal, is ideal for conservative designs aiming to convey stability, reliability, and abundance.",
  },
  {
    id: 31,
    vibe: "Artistic",
    color: "Pink",
    title: "Bright Pink and Pastels",
    owner: "Stinkdigital",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website31.jpg",
    colorA: "#E64398",
    colorB: "#A1C3D1",
    industry: "Creative",
    description:
      "This lively site brings together a bright raspberry pink with softer colors such as pastel blue and light pastel purple. The result is a wonderfully fresh and lighthearted color scheme.",
  },
  {
    id: 32,
    vibe: "Vintage",
    color: "Red/Raspberry",
    owner: "AILOVE",
    title: "Unique Combination",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website32.jpg",
    colorA: "#59253A",
    colorB: "#78244C",
    industry: "Technology",
    description:
      "This unlikely blend of a range of dark pinks with a blues makes this a unique and engaging combination that can be used for a range of projects in different fields.",
  },
  {
    id: 33,
    vibe: "Modern",
    color: ["Black", "Dark", "Yellow"],
    owner: "Superhero Cheesecake",
    title: "Striking Citrus Colors",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website33.jpg",
    colorA: "#D6CE15",
    colorB: "#1F2605",
    industry: "Sports",
    description:
      "This fresh and citrusy blend of light greenish-yellows, lime green and black is a favorite among brands related to high-adrenaline sports and energy drinks.",
  },
  {
    id: 34,
    vibe: "Lively",
    color: ["Blue", "Green"],
    owner: "Burocratik",
    title: "Vivid Blues and Orange",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website34.jpg",
    colorA: "#10E7DC",
    colorB: "#6CDAEE",
    industry: "Technology",
    description:
      "The bright turquoise background and orange call-to-action button on this site may be a bit loud for some visitors, but the combination definitely conveys high-energy emotions, which go along with the image in the background.",
  },
  {
    id: 35,
    vibe: "Earthy",
    color: "Red/Raspberry",
    owner: "Google Brand Studio",
    title: "Rose Red and Blueberry",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website35.jpg",
    colorA: "#BC4639",
    colorB: "#D4A59A",
    industry: "Creative",
    description:
      "This range of pinks and reds with a bright blue call-to-action button creates plenty of visual interest and draws attention to itself immediately.",
  },
  {
    id: 36,
    vibe: "Modern",
    industry: "Corporate",
    color: "Blue",
    owner: "Details",
    title: "Audacious and Unique",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website36.jpg",
    colorA: "#0D19A3",
    colorB: "#E4C580",
    description:
      "This bold and unique combination of royal blue and gold, with vivid cyan highlights, captures the eye. Its unexpected and somewhat out-of-the-box thinking help make this website a winner.",
  },
  {
    id: 37,
    vibe: "Lively",
    color: "Yellow",
    owner: "Cher Ami",
    title: "Cheerful and Energetic",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website37.jpg",
    colorA: "#FBE8AC",
    colorB: "#D2FDFF",
    industry: "Healthcare",
    description:
      "The cyan, blues and oranges on this page make this a particularly inviting and energetic design that can be applied to projects with an optimistic and uplifting message.",
  },
  {
    id: 38,
    vibe: "Calm",
    color: "Blue",
    owner: "Leavingstone",
    title: "Snowy Yet Warm",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website38.jpg",
    colorA: "#3B8BEB",
    colorB: "#B23850",
    industry: "Education",
    description:
      "This wintery red and blue combination evokes both coolness and warmth at the same time, similar to images related to the winter holidays.",
  },
  {
    id: 39,
    vibe: "Artistic",
    color: ["Red/Raspberry", "Yellow", "Beige/Light"],
    owner: "Elespacio",
    title: "Rich and Colorful",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website39.jpg",
    colorA: "#90CCF4",
    colorB: "#ECECEC",
    industry: "Creative",
    description:
      "This bright and rich color combination brings together a vivid yellow, blue and pink in this beautiful minimalist design, which can be used in lively yet professional projects.",
  },
  {
    id: 40,
    vibe: "Modern",
    color: ["Drak", "Black"],
    owner: "SFCD",
    title: "Modern and Minimalist",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website40.jpg",
    colorA: "#19181A",
    colorB: "#A16E83",
    industry: "E-commerce",
    description:
      "This site pulls off an attractive design with just a few elements and a well-chosen color scheme. Turkish rose, middle green and yellow geometric shapes over a black and gray background are enough to catch the viewer's eye.",
  },
  {
    id: 41,
    vibe: "Vintage",
    industry: "Corporate",
    color: "Red/Raspberry",
    title: "Intrepid and Fearless",
    owner: "Great Works Copenhagen",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website41.jpg",
    colorA: "#C96567",
    colorB: "#314455",
    description:
      "This effective color combination utilizes shades of blue and red to evoke a sense of boldness and ardent professionalism, making it perfect for designs aiming to convey power and competence.",
  },
  {
    id: 42,
    owner: "Resn",
    color: ["Blue", "White/Creamy"],
    vibe: "Artistic",
    title: "Flat Design Colors",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website42.jpg",
    colorA: "#77A6F7",
    colorB: "#00887A",
    industry: "Education",
    description:
      "As seen here, flat design colors typically lean towards being very bright and highly saturated. Even though the site above adds a slight shadow effect to the boy on the right, it still falls within the realm of flat design 2.0, where subtle three-dimensional effects are occasionally incorporated.",
  },
  {
    id: 43,
    owner: "Play",
    color: ["Slate Gray", "Beige/Light"],
    vibe: "Lively",
    title: "Eclectic and Peaceful",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website43.jpg",
    colorA: "#86B3D1",
    colorB: "#AAA0A0",
    industry: "E-commerce",
    description:
      "This distinctive blend of coffee tones paired with sky blue and various shades of brown creates a soothing and comforting color scheme, reminiscent of a cozy coffee house or lounge ambiance.",
  },
  {
    id: 44,
    vibe: "Calm",
    industry: "Corporate",
    color: ["Blue", "Beige/Light", "Slate Gray"],
    owner: "details.ch",
    title: " Classy and Traditional",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website44.jpg",
    colorA: "#5F6366",
    colorB: "#4D6D91",
    description:
      "The combination of cameo pink, UCLA blue, and granite gray evokes the attire associated with well-to-do, preppy college students. This scheme not only resonates with the site's target audience but also offers a blend of seriousness and liveliness that can enhance any design aiming for a sophisticated yet vibrant aesthetic.",
  },
  {
    id: 45,
    vibe: "Lively",
    color: "Dark",
    owner: "stinkdigital",
    title: "Accent Colors That Pop",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website45.jpg",
    colorA: "#2D283E",
    colorB: "#802BB1",
    industry: "Creative",
    description:
      "This Spotify site perfectly utilizes a grape-colored accent against a very dark, desaturated violet background. This color scheme is ideal for designs where you want specific elements or a central message to stand out prominently.",
  },
  {
    id: 46,
    vibe: "Vintage",
    industry: "Corporate",
    color: "Blue",
    owner: "EPIC",
    title: "Corporate and Serious",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website46.jpg",
    colorA: "#265077",
    colorB: "#022140",
    description:
      "Oxford blue, complemented by bright blue and red highlights, gives this site a traditional and corporate feel. Blue and green, colors often associated with professionalism and stability, are commonly used in corporate reports to convey these qualities.",
  },
  {
    id: 47,
    vibe: "Modern",
    color: "White/Creamy",
    owner: "Apart",
    title: "Glamorous and Fashion-Forward",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website47.jpg",
    colorA: "#33266E",
    colorB: "#111111",
    industry: "Creative",
    description:
      "This blend of gold, purple, and black evokes a sense of wealth and extravagance. Consequently, this color combination is well-suited for designs related to fashion, luxury, and high-end products.",
  },
  {
    id: 48,
    vibe: "Vintage",
    color: "Black",
    owner: "FUTURAMO",
    title: "Eye-Catching and Sleek",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website48.jpg",
    colorA: "#CB2D6F",
    colorB: "#CCCCCC",
    industry: "Education",
    description:
      "The color scheme of this website revolves around a series of interlaced gradient circles, creating a vibrant palette. Dominated by sky blue, salmon-pink, and bright orange as primary hues, it also features accent colors in black and neon green strategically used to highlight crucial information such as dates and calls to action. This blend of colors not only enhances visual appeal but also ensures key elements stand out effectively.",
  },
  {
    id: 49,
    vibe: "Artistic",
    color: ["Pink", "Green"],
    owner: "Panic",
    title: "Loud and In-Your-Face",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/website49.jpg",
    colorA: "#16FFBD",
    colorB: "#F070A1",
    industry: "Technology",
    description:
      "Unlike the previous, more subdued color scheme, this combination is intentionally loud and vibrant, which might not appeal to everyone. However, when aiming to make a bold statement, this scheme can be highly effective if executed correctly, as demonstrated here.",
  },
  {
    id: 50,
    vibe: "Calm",
    color: ["Yellow", "Beige/Light"],
    owner: "madeo",
    title: " Lively Yet Soothing",
    image: "https://visme.co/blog/wp-content/uploads/2016/09/11.jpg",
    colorA: "#244855",
    colorB: "#FBE9D0",
    industry: "Sports",
    description:
      "This relaxing yet cheerful combination of lemon yellow, mint, and dark cyan creates an ideal color scheme for conveying energy, optimism, and harmony. Perfect for messages focused on growth and positivity, this palette strikes a balance between vibrant energy and soothing calmness.",
  },
];

const uniqueColors = [...new Set(images.flatMap((image) => image.color))];
const uniqueVibes = [...new Set(images.map((image) => image.vibe))];
const uniqueIndustries = [...new Set(images.map((image) => image.industry))];

export { images, uniqueColors, uniqueVibes, uniqueIndustries };
